### ISSUE TITLE
The deployment configuration wizard fails to persist Liferay's path

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#1013]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [X] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [X] :three: v3.x

### Description

```
C:\Werk\Clientes\PRODESP\test>liferay deploy
Building project for target platform: @liferay/dxp-7.3
:information_source: Copying 0 assets...
:information_source: Running sass on 1 asset files...
:information_source: Running babel on 2 files...
:information_source: Running liferay-npm-bundler...
Bundling took 246ms
:heavy_check_mark: Project successfully built
Deploying project to Liferay local installation

:warning: There's no deploy configuration for the project yet

:information_source: The Deploy configuration wizard will be run before doing anything.

:wave: Welcome to the Deploy configuration wizard

The wizard will ask you some questions to configure how the deploy command
behaves.

You may accept the default values for any setting you don't want to modify.

? What is the path to your local Liferay installation? C://Werk/Clientes/ICETEX/liferay-dxp-7.3.10-ga1
C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\js-toolkit-core\lib\project\liferayCli\persist.js:30
            throw new Error(`Invalid location: ${location}`);
                  ^

Error: Invalid location: undefined
    at persist (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\js-toolkit-core\lib\project\liferayCli\persist.js:30:19)
    at Deploy.storeDir (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\js-toolkit-core\lib\project\liferayCli\Deploy.js:27:31)
    at C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\portal-base\lib\configureDeploy.js:36:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runConfigureWizard (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\portal-base\lib\util\runConfigureWizard.js:17:5)
    at async configureDeploy (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\portal-base\lib\configureDeploy.js:15:5)
    at async Object.deploy (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\portal-base\lib\deploy.js:18:9)
    at async run (C:\Werk\Clientes\PRODESP\test\node_modules\@liferay\portal-base\lib\index.js:64:17)
```

**Comment by izaera** [comment]
For the record: internal slack conversation -> https://liferay.slack.com/archives/CNBG06JS3/p1664318701387739
