### ISSUE TITLE
lnbs-start: Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by mahavir1408** [liferay/liferay-frontend-projects#188]
Hello Team, 
I am trying to run "lnbs-start" command. However, I am getting the below error.
```
ERROR in ../src/index.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: C:\code\projects\dtp-actions\src\index.js: Support for the experimental syntax 'jsx' isn't currently enabled (20:9):

  18 |
  19 |     ReactDOM.render(
> 20 |         <AppComponent
     |         ^
  21 |             portletNamespace={portletNamespace}
  22 |             contextPath={contextPath}
  23 |             portletElementId={portletElementId}

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:766:17)
    at Parser.raiseWithData (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:759:17)
    at Parser.expectOnePlugin (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:8981:18)
    at Parser.parseExprAtom (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:10276:22)
    at Parser.parseExprSubscripts (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9844:23)
    at Parser.parseUpdate (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9824:21)
    at Parser.parseMaybeUnary (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9813:17)
    at Parser.parseExprOps (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9683:23)
    at Parser.parseMaybeConditional (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9657:23)
    at Parser.parseMaybeAssign (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9620:21)
    at C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9586:39
    at Parser.allowInAnd (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:11303:12)
    at Parser.parseMaybeAssignAllowIn (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9586:17)
    at Parser.parseExprListItem (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:11051:18)
    at Parser.parseCallExpressionArguments (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:10053:22)
    at Parser.parseCoverCallAndAsyncArrowHead (C:\code\projects\dtp-actions\node_modules\@babel\parser\lib\index.js:9960:29)
 @ ./index.js 1:11-37

i ∩╜ówdm∩╜ú: Failed to compile.

```

Here is the package.json 
```
{
	"name": "dtp-actions",
	"version": "1.0.0",
	"description": "Dtp Actions",
	"devDependencies": {
		"@babel/cli": "^7.10.5",
		"@babel/core": "^7.11.4",
		"@babel/plugin-proposal-class-properties": "^7.10.4",
		"@babel/preset-env": "^7.11.0",
		"@babel/preset-react": "^7.10.4",
		"babel-loader": "^8.1.0",
		"copy-webpack-plugin": "4.6.0",
		"css-loader": "^4.2.2",
		"file-loader": "^6.1.0",
		"liferay-npm-build-support": "^2.19.1",
		"liferay-npm-bundler": "^2.19.1",
		"node-sass": "^4.14.1",
		"sass-loader": "^10.0.1",
		"style-loader": "^1.2.1",
		"webpack": "^4.44.1",
		"webpack-cli": "^3.3.12",
		"webpack-dev-server": "^3.11.0"
	},
	"dependencies": {
		"react": "^16.13.1",
		"react-dom": "^16.13.1",
		"axios": "^0.20.0",
		"bootstrap": "^4.5.2",
		"normalize.css": "^8.0.1",
		"react-router-dom": "^5.2.0"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"start": "lnbs-start"
	},
	"main": "index.js"
}

```
The .babelrc file
```
{
	"presets": [
	  "@babel/preset-react",
	  [
		"@babel/preset-env",
		{
		  "useBuiltIns": "entry"
		}
	  ]
	],
	"plugins": ["@babel/plugin-proposal-class-properties"]
}
```

The .npmbuildrc file
```
{
	"webpack": {
		"rules": [{
				"loader": "babel-loader",
				"test": "\\.js$",
				"exclude": "/node_modules/"
			},
			{
				"test": "src\\\\.*\\.js$",
				"use": "babel-loader"
			},
			{
				"test": "\\.(sa|sc|c)ss$",
				"use": ["style-loader", "css-loader", "sass-loader"]
			},
			{
				"test": "\\.(woff|woff2|eot|ttf|otf)$",
				"use": ["file-loader"]
			}
		]
	}
}
```

**Comment by DanEdwards-JM** [comment]
- `npm run start eject`
- Edit `rules` in `webpack.config.js` to:

```js
rules: [
  {
    test: /src\/.*\.js$/,
    use: {
      loader: "babel-loader",
      options: { configFile: "../.babelrc" },
    },
  },
],
```
