### ISSUE TITLE
Theme fails to deploy to Docker Container

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-frontend-projects#269]
At first I was unable to deploy a Theme to the Docker container at all, even manually. I had to set up a Bind Mount, and only then did it work. `npm run deploy` fails with this error:

```
[11:48:32] Using gulpfile ~\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\gulpfile.js
[11:48:32] Starting 'deploy'...
[11:48:32] Starting 'build'...
[11:48:32] Starting 'build:clean'...
[11:48:32] Finished 'build:clean' after 289 ms
[11:48:32] Starting 'build:base'...
[11:48:40] Finished 'build:base' after 8.06 s
[11:48:40] Starting 'build:src'...
[11:48:40] Finished 'build:src' after 34 ms
[11:48:40] Starting 'build:web-inf'...
[11:48:40] Finished 'build:web-inf' after 843 μs
[11:48:40] Starting 'build:liferay-look-and-feel'...
[11:48:40] Finished 'build:liferay-look-and-feel' after 15 ms
[11:48:40] Starting 'build:hook'...
[11:48:40] Finished 'build:hook' after 5.77 ms
[11:48:40] Starting 'build:themelets'...
[11:48:40] Starting 'build:themelet-src'...
[11:48:41] Finished 'build:themelet-src' after 786 μs
[11:48:41] Starting 'build:themelet-css-inject'...
[11:48:41] Starting 'build:themelet-js-inject'...
[11:48:41] gulp-inject Nothing to inject into _custom.scss.
[11:48:41] gulp-inject Nothing to inject into portal_normal.ftl.
[11:48:41] Finished 'build:themelet-css-inject' after 98 ms
[11:48:41] Finished 'build:themelet-js-inject' after 35 ms
[11:48:41] Finished 'build:themelets' after 127 ms
[11:48:41] Starting 'build:rename-css-dir'...
[11:48:41] Finished 'build:rename-css-dir' after 2.2 ms
[11:48:41] Starting 'build:compile-css'...
[11:48:41] Starting 'build:compile-lib-sass'...
[11:48:45] Finished 'build:compile-lib-sass' after 4.46 s
[11:48:45] Finished 'build:compile-css' after 4.46 s
[11:48:45] Starting 'build:fix-url-functions'...
[11:48:45] Finished 'build:fix-url-functions' after 49 ms
[11:48:45] Starting 'build:move-compiled-css'...
[11:48:46] Finished 'build:move-compiled-css' after 794 ms
[11:48:46] Starting 'build:remove-old-css-dir'...
[11:48:46] Finished 'build:remove-old-css-dir' after 81 ms
[11:48:46] Starting 'build:fix-at-directives'...
[11:48:46] Finished 'build:fix-at-directives' after 36 ms
[11:48:46] Starting 'build:r2'...
[11:48:46] Finished 'build:r2' after 177 ms
[11:48:46] Starting 'build:copy:fontAwesome'...
[11:48:46] Finished 'build:copy:fontAwesome' after 61 ms
[11:48:46] Starting 'build:war'...
[11:48:46] Starting 'plugin:version'...
[11:48:46] Finished 'plugin:version' after 3.95 ms
[11:48:46] Starting 'plugin:war'...
[11:48:52] Finished 'plugin:war' after 5.94 s
[11:48:52] Finished 'build:war' after 5.95 s
[11:48:52] Finished 'build' after 20 s
[11:48:52] Starting 'deploy:war'...
[11:48:52] Starting 'deploy:docker'...
sh: tar xp -C 1468d2530957:/mnt/liferay/files/deploy: not found

C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\liferay-theme-tasks\tasks\deploy.js:46
                                if (err) throw err;
                                         ^

Error: spawnSync C:\WINDOWS\system32\cmd.exe EOF
    at Object.spawnSync (internal/child_process.js:990:20)
    at spawnSync (child_process.js:601:24)
    at Function.spawnSync [as sync] (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\cross-spawn\index.js:45:14)
    at tar.pack.pipe.es.wait (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\liferay-theme-tasks\lib\util.js:65:23)
    at Stream.<anonymous> (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\event-stream\index.js:345:20)
    at _end (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\through\index.js:74:5)
    at Pack.onend (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\tar-stream\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at Pack.emit (events.js:189:13)
    at endReadableNT (C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme\node_modules\tar-stream\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-liferay-theme@1.0.0 deploy: `gulp deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-liferay-theme@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\liferay\AppData\Roaming\npm-cache\_logs\2020-02-21T16_48_53_145Z-debug.log

C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme>npm run deploy

> my-liferay-theme@1.0.0 deploy C:\Users\liferay\Desktop\projects\docs\liferay-learn-7.x-docs\my-liferay-theme
> gulp deploy
```

**Comment by nil0blue** [comment]
We have another customer that ran into the same problem.

**Comment by izaera** [comment]
Seeing this is a recurrent issue, just a brief note to state that we’re looking at how to better support this in the long term but it is low priority in the project's backlog.

Nevertheless, we’ll happily accept contributions or additional help :-).

**Comment by JamesAGarcia** [comment]
I just experienced similar issues when attempting to deploy an activation key (I'm on Windows). 

Whenever I attempted to deploy an XML key to my container using the `docker cp` command in powershell, the console repeats the following error msg over and over:

```log
ERROR [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:252] Unable to write activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```

However, I can successfully deploy the same key using a bind mount, or the `docker cp` command in my WSL distro. It seems to be a permissions problem.

Here's a summary of what I found--hope it's helpful for when you get around to this ticket:

## When Deployed with `docker cp` (Windows)

These are the permissions of the keys that failed to write to my docker container when I used the `docker cp activation-key-dxpdevelopment-7.3-developeractivationkeys.xml lrtest:/opt/liferay/deploy` command:

```bash
-rw-r--r-- 1 Liferay 197121 840 Feb 24 14:08 activation-key-commercesubscriptiondevelopment-1-developeractivationkeys.xml
-rw-r--r-- 1 Liferay 197121 869 Feb 25 16:39 activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```
 
Here are the permissions of the same keys in the  `opt/liferay/deploy` folder:

```bash
-rwxr-xr-x    1 root     root           840 Feb 24 14:08 activation-key-commercesubscriptiondevelopment-1-developeractivationkeys.xml
-rwxr-xr-x    1 root     root           869 Feb 25 16:39 activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```
The owner is `root`, and they do not have the necessary permissions.

## When Deployed with Bind Mount (Windows)

Here are the permissions of the same keys in the `opt/liferay/deploy` folder when added using a bind mount

```bash
-rwxrwxrwx    1 root     root           840 Feb 24 22:08 activation-key-commercesubscriptiondevelopment-1-developeractivationkeys.xml
-rwxrwxrwx    1 root     root           869 Feb 26 00:39 activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```

The owner is `root`, but they have all the necessary permissions.

## When Deployed with `docker cp` (WSL)

Here are the permissions of the same 

```bash
-rwxrwxrwx 1 james james 840 Feb 24 14:08 activation-key-commercesubscriptiondevelopment-1-developeractivationkeys.xml
-rwxrwxrwx 1 james james 869 Feb 25 16:39 activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```

When added to the `opt/liferay/deploy` folder, they have the following permissions, and their owner is `liferay`.

```bash
-rwxrwxrwx    1 liferay  liferay        840 Feb 24 22:08 activation-key-commercesubscriptiondevelopment-1-developeractivationkeys.xml
-rwxrwxrwx    1 liferay  liferay        869 Feb 26 00:39 activation-key-dxpdevelopment-7.3-developeractivationkeys.xml
```
