### ISSUE TITLE
Figure out why exit status is gettings swallowed for Yarn 1.13.0 but not 1.25.0

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#378]
### Issue type

-   :bug: Bug report

### Description

As noted [here](https://github.com/andrea-ale-sbarra/liferay-portal/pull/4#discussion_r549744036), exit status is getting swallowed during build in `modules/apps/commerce/commerce-product-options-web`, but you can repro anywhere as long as you use an old version of `yarn`.

My comment on the thread follows:

---

Ugh — it must be something to do with the ~Gradle environment~ Yarn version; I only see `UnhandledPromiseRejectionWarning` and the false `BUILD SUCCESSFUL` from Gradle.

When I fetch this PR and `cd` into `modules/apps/commerce/commerce-product-options-web`, I see `yarn build` exit like this (edited for brevity):

```
yarn run v1.22.5
warning package.json: No license field
$ liferay-npm-scripts build
Using NODE_ENV: "production"
{ SyntaxError: /Users/greghurrell/code/portal/liferay-portal/modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/ProductOptions.js: Unexpected token (31:46)

  29 |  };
  30 |
> 31 |  nameInput.addEventListener('input', debounce.(handleOnNameInput, 200));
     |                                               ^
  32 |
  33 |  document
  34 |          .getElementById( namespace +'publishButton')
    at Object._raise (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@babel/parser/lib/index.js:763:17)
  loc: Position { line: 31, column: 46 },
  pos: 1091,
  code: 'BABEL_PARSE_ERROR' }
Command /Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/babel --no-babelrc --config-file /Users/greghurrell/code/portal/liferay-portal/modules/apps/commerce/commerce-product-options-web/build/npmscripts/tmp/.babelrc src/main/resources/META-INF/resources --out-dir build/node/packageRunBuild/resources --source-maps exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
zsh: exit 1     yarn build
```

But when I run via Gradle, the error gets printed but the build spuriously claims success (again, edited for brevity):

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
> Task :yarnInstall
> Task :apps:commerce:commerce-product-options-web:packageRunBuild
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: "development"
{ SyntaxError: /Users/greghurrell/code/portal/liferay-portal/modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/ProductOptions.js: Unexpected token (31:46)

  29 |  };
  30 |
> 31 |  nameInput.addEventListener('input', debounce.(handleOnNameInput, 200));
     |                                               ^
  32 |
  33 |  document
  34 |          .getElementById( namespace +'publishButton')
    at Object._raise (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@babel/parser/lib/index.js:763:17)
(node:14966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 4.94s.

> Task :apps:commerce:commerce-product-options-web:processResources
> Task :apps:commerce:commerce-product-options-web:deployConfigs NO-SOURCE

BUILD SUCCESSFUL in 49s
8 actionable tasks: 8 executed
```

So, just checking to see whether it is due to the liferay-portal version of Yarn (v1.13.0) vs the one I was using when I ran `yarn build` (v1.22.5), it seems like it is:

```
$ portool yarn run build
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts build
Using NODE_ENV: "production"
{ SyntaxError: /Users/greghurrell/code/portal/liferay-portal/modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/ProductOptions.js: Unexpected token (31:46)

  29 |  };
  30 |
> 31 |  nameInput.addEventListener('input', debounce.(handleOnNameInput, 200));
     |                                               ^
  32 |
  33 |  document
  34 |          .getElementById( namespace +'publishButton')
    at Object._raise (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@babel/parser/lib/index.js:763:17)
  loc: Position { line: 31, column: 46 },
  pos: 1091,
  code: 'BABEL_PARSE_ERROR' }
(node:15114) UnhandledPromiseRejectionWarning: Error: Command /Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/babel --no-babelrc --config-file /Users/greghurrell/code/portal/liferay-portal/modules/apps/commerce/commerce-product-options-web/build/npmscripts/tmp/.babelrc src/main/resources/META-INF/resources --out-dir build/node/packageRunBuild/resources --source-maps exited with code 1
    at spawnSync (/Users/greghurrell/code/portal/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/utils/spawnSync.js:42:9)
(node:15114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 3.74s.
```

**Comment by wincent** [comment]
Ok, got to the bottom of this. The Yarn version difference was a red herring. This was fixed in d6ab2974c (https://github.com/liferay/liferay-frontend-projects/pull/259) which was released in [v36.3.0](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.3.0). 

[liferay-portal](https://github.com/liferay/liferay-portal) is already [on v36.7.0](https://github.com/liferay/liferay-portal/blob/65ca1519b40665f44ca2aca56108deb998031278/modules/package.json#L3). I think the reason [that PR](https://github.com/andrea-ale-sbarra/liferay-portal/pull/4) was seeing the silent failures is because it is based on an old commit where [the `package.json` is still pointing at v36.2.0](https://github.com/andrea-ale-sbarra/liferay-portal/blob/e55ca8a22693d76ceefb8351487b93a9381d30fd/modules/package.json#L3).
