### ISSUE TITLE
Unable to build an adapted Vue.js project with js-toolkit version 2.28.3

### ISSUE THREAD

**Issue by pandeytanmay** [liferay/liferay-frontend-projects#837]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description

**Desired behavior:**
`npm run build:liferay` on an adapted vuejs project should run successfully and generate a jar deployable to Liferay. 
**Current behavior:**
Running npm run build:liferay results in the following error:

```
`internal/fs/utils.js:269
throw err;
^

Error: ENOENT: no such file or directory, scandir '<projectBaseDir(redacted)>\build\static\js'
at Object.readdirSync (fs.js:955:3)
at buildWith (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\lib\scripts\build\index.js:63:14)
at Object.default_1 [as default] (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\lib\scripts\build\index.js:42:13)
at Object. (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\bin\lnbs-build.js:8:40)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47 {
errno: -4058,
syscall: 'scandir',
code: 'ENOENT',
path: '<projectBaseDir(redacted)>\build\static\js'
}`
```

**Repro instructions (if applicable):**
 Here is how to recreate the problem:

Install node : v12.22.1

Install npm : 6.14.12

Run the following from command prompt in sequence:

```
npm i -g @vue/cli

npm install -g yo 
npm install -g generator-liferay-js

vue create hello-world

cd hello-world
```
(Select vue 2 while creating this new project)
`yo liferay-js:adapt`
(select appropriate options while running the preceding command (yo liferay-js:adapt))

```
npm install

npm run build:liferay
```

**Other information (environment, versions etc):**
Node version : v12.22.1

npm version : 6.14.12
vue version : vue@2.6.14

**Comment by pandeytanmay** [comment]
#809

**Comment by izaera** [comment]
Looks like migration from Vue 2 to 3 it's not an easy task (see [this article](https://vueschool.io/articles/news/which-vue-js-version-to-use-in-2021-and-why/) and [this one](https://crisp.chat/blog/vuejs-migration/), for example) so it may make sense to support both vue 2 and 3 adaptation for some time.

What do you think @bryceosterhaus, @dsanz and @pablo-agulla ? :thinking:

**Comment by bryceosterhaus** [comment]
@izaera I think it probably makes sense to support both 2 & 3 for a period of time, although we way want to have some sort of cut off date for vue 2 support. It may even make sense to only support 2.x for now as the official site still points to 2.x and only a subdomain points to 3.x. This is a slippery slope for us though as we don't want to get in a habit of supporting multiple major versions of each framework.

**Comment by pablo-agulla** [comment]
@izaera and @bryceosterhaus I agree with your ideas. As long as 2.x version is a big portion of the use, we should support it. We could wait for 3.x support until it gets some usage: https://w3techs.com/technologies/details/js-vuejs As for maintaining multiple versions, is not ideal, but depending on usage is something that we should do. For example in our mobile tools, we kept compatibility with Android and iOS for up to 5-6 versions.
