### ISSUE TITLE
@liferay/cli - Build error with Node versions 16.15.0 and 14.18.1

### ISSUE THREAD

**Issue by WHI-CH** [liferay/liferay-frontend-projects#923]
Globally installed package on Windows always throws the following error when trying to build a generated React project for DXP 7.4 (no source changes):

```liferay build
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '<project_path>\node_modules\ansis\src\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (<project_path>\node_modules\webpack-remove-empty-scripts\src\index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '<project_path>\\node_modules\\ansis\\package.json',
  requestPath: 'ansis'
}

**Comment by izaera** [comment]
We use the webpack-remove-empty-scripts plugin to remove comments from the final output. And ansis is a dependency of it.
I would say the package is broken or npm has failed to download everything.

Can you try to download everything (node_modules) again or play with npm (yarn resolutions could do it) to download an older version of ansis? Then report your findings.

Thx.

**Comment by WHI-CH** [comment]
Ok, using Yarn and switching to Node 16.13.2 (with nvm) works.
Good enough for now, thanks for the reply!

**Comment by izaera** [comment]
Glad to know it was fixed :-)
