### ISSUE TITLE
@liferay/cli - Error when building React project with TypeScript on Windows

### ISSUE THREAD

**Issue by WHI-CH** [liferay/liferay-frontend-projects#956]
The following error occurs when trying to build a React project with TypeScript on Windows:
```
Building project for target platform: @liferay/dxp-7.4
ℹ️ Copying 27 assets...
ℹ️ Running sass on 1 asset files...
ℹ️ Running tsc compiler...

Error: spawnSync npx ENOENT
    at Object.spawnSync (node:internal/child_process:1083:20)
    at Object.spawnSync (node:child_process:812:24)
    at spawn (<project_path>\node_modules\@liferay\portal-base\lib\util\spawn.js:16:58)
    at runTsc (<project_path>\node_modules\@liferay\portal-base\lib\build\bundler2.js:161:22)
    at runCompiler (<project_path>\node_modules\@liferay\portal-base\lib\build\bundler2.js:139:3)
    at bundler2 (<project_path>\node_modules\@liferay\portal-base\lib\build\bundler2.js:71:2)
    at Object.build (<project_path>\node_modules\@liferay\portal-base\lib\build\index.js:26:34)
    at run (<project_path>\node_modules\@liferay\portal-base\lib\index.js:40:16)
    at Object.<anonymous> (<project_path>\node_modules\@liferay\dxp-7.4\liferay.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

❌ Build failed
```
The `runTsc()` function in _bundlers2.js_ is the problem. I found [this info](https://github.com/nodejs/node/issues/8077#issuecomment-240602671) and changed it to the following, so the _npx_ command is called using _npx.cmd_:
```
function runTsc() {
	print(info`Running {tsc} compiler...`);
	(0, spawn_1.default)('npx.cmd', ['tsc']);
}
```
I think the `{shell: true}` option would be the cross-platform way to fix this? I haven't found a way to get that to work here though...

**Comment by bryceosterhaus** [comment]
What versions of node and npm are you using?

**Comment by WHI-CH** [comment]
node -v
v16.13.2
npm -v
8.1.2

**Comment by WHI-CH** [comment]
Any news on this? Right now the CLI is useless on Windows and anyone using TypeScript in their projects will hopefully know how to compile it before calling _liferay build_

**Comment by WHI-CH** [comment]
Ah, thanks for the info!
So the problem is just that the [@liferay/portal-base](https://www.npmjs.com/package/@liferay/portal-base) npm package hasn't received this update yet.

**Comment by izaera** [comment]
Right. `@liferay/portal-base` 1.1.1 ([latest version](https://www.npmjs.com/package/@liferay/portal-base)) is from Feb 2022 (https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-base%2Fv1.1.1) while the commit @bryceosterhaus is linking if from March 2022.

I'm going to release a new version of `@liferay/portal-base` to fix this :+1: .

**Comment by izaera** [comment]
Done -> https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-base%2Fv1.2.0

**Comment by izaera** [comment]
@WHI-CH Please check if that works :+1:

**Comment by WHI-CH** [comment]
Yes, looks good, thanks!
